version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  flower:
    image: mher/flower
    container_name: celery_flower
    command: >
      celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:

