apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
  labels:
    name: nginx-storage
    lastname: Grasso
spec:
  containers:
  - image: nginx:latest
    name: nginx
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir:
      sizeLimit: 500Mi
