version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: test-buffer
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge

