services:
  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: gcs-emulator
    ports:
      - "4443:4443"
    command:
      - "-scheme=http"
      - "-port=4443" 
      - "-external-url=http://localhost:4443"
      - "-data=/storage"
      - "-backend=filesystem"
    volumes:
      - ./gcs-data:/storage:rw
    environment:
      - STORAGE_BASE=/storage
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4443/storage/v1/b"]
      interval: 10s
      timeout: 5s
      retries: 3
